{% set name = "gocart" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 879fe060594347b6a39ab8aad7fcabbdd0502f0af0ff46286781747aaf7f42dd

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - "gocart = gocart.cl_utils:main"

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - fundamentals
    - python >=3.9
    - pyyaml
    - astropy==5.1.0,
    - astropy-healpix
    - numpy
    - matplotlib
    - healpy
    - pandas
    - tabulate
    - ligo.skymap
    - gcn-kafka

test:
  imports:
    - gocart

about:
  home: https://github.com/thespacedoctor/gocart
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: "Listen for, collect and convert multimessenger skymaps"
  doc_url: https://gocart.readthedocs.io
  dev_url: https://github.com/thespacedoctor/gocart

extra:
  recipe-maintainers:
    - thespacedoctor
